### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by robertostling** [proiel/proiel-cli#3]
I get a syntax error when trying to run the CLI, installed through `gem install proiel-cli`.

This is on a Debian stable system. Ruby version and error output below:

```
$ ruby --version
ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]

$ proiel
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /var/lib/gems/2.1.0/gems/proiel-cli-0.1.0/lib/proiel/cli/converters/proielxml.rb:91: syntax error, unexpected ':', expecting ')' (SyntaxError)
...     builder.slash("target-id": target_id, relation: relatio...
...                               ^
/var/lib/gems/2.1.0/gems/proiel-cli-0.1.0/lib/proiel/cli/converters/proielxml.rb:152: syntax error, unexpected end-of-input, expecting keyword_end
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
...
```

**Comment by daghaug** [comment]
I get the same error with ruby 2.1.5, but it works in ruby 2.2.3, so we 
should make this clear in the documentation.
